spring.application.name=ms-usuarios

server.port=8080

spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.aegfjfdnpqxtqvnqvyok
spring.datasource.password=@Jose2205200
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=MiClaveSuperSecretaParaConvocatoriasUSCO2026
jwt.expiration=86400000